#!/usr/bin/env bash
# Adds new attribute "address" to all documents where name="Holberton school"
mongo "$1" --quiet --eval 'db.school.updateMany(
  { name: "Holberton school" },
  { $set: { address: "972 Mission street" } }
)'

